### ISSUE TITLE
"connect" functions unconditionally println! debugging info

### ISSUE THREAD

**Issue by MartijnVdS** [lukaskirner/tokio-sunspec#4]
The `println!` in the `connect_{rtu,tcp}` functions are getting in the way of my program's other output.

I would like to propose replacing them with `std::log::info` (https://docs.rs/log/latest/log/), so it's still possible to get the messages if required, but it's also possible to turn them off (or redirect them).

If you agree I'll make a PR to implement this.

**Comment by lukaskirner** [comment]
I removed all `print` statements in the latest release
